name: Docs → GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Build site (MkDocs)
        run: poetry run mkdocs build --strict

      - name: Move default build to /en/ and create redirect
        run: |
          # Move built English docs (from root) to /en/
          mkdir -p site/en
          # Move all root files/dirs except de/ and assets/ to /en/
          for item in site/*; do
            base=$(basename "$item")
            if [ "$base" != "de" ] && [ "$base" != "assets" ] && [ "$base" != "en" ]; then
              mv "$item" site/en/
            fi
          done

          # Create root redirect to /en/
          cat > site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Redirecting to Aqtra Docs</title>
            <meta http-equiv="refresh" content="0; URL=/en/">
            <link rel="canonical" href="https://docs.aqtra.io/en/">
            <script>window.location.replace("/en/" + window.location.hash);</script>
          </head>
          <body>
            <p>Redirecting to <a href="/en/">Aqtra Documentation</a>...</p>
          </body>
          </html>
          EOF

      - name: Add CNAME and .nojekyll
        run: |
          echo "docs.aqtra.io" > site/CNAME
          touch site/.nojekyll

      - name: Verify build output
        run: |
          echo "Root structure:"
          ls -la site | sed -n '1,20p'
          echo ""
          echo "Checking critical files:"
          test -f site/index.html && echo "✅ Root index.html (redirect)"
          test -f site/en/index.html && echo "✅ EN index.html"
          test -f site/de/index.html && echo "✅ DE index.html"
          test -f site/CNAME && echo "✅ CNAME"
          test -f site/.nojekyll && echo "✅ .nojekyll"
          echo ""
          echo "/en/ structure:"
          ls -la site/en | sed -n '1,15p'

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
